modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "separatedleaves"
version = "${version}"
displayName = "Separated Leaves"
authors = "LarsMans"
description = '''
This mod makes leaves only connect to their own log type
'''
logoFile = "icon.png"

[[dependencies.example_mod]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.example_mod]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.example_mod]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "separatedleaves-common.mixins.json"

[[mixins]]
config = "separatedleaves.mixins.json"
